# Generated by Django 4.2.3 on 2023-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_assignment_lesson_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='quiz.assignment'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=None),
        ),
    ]
