# Generated by Django 4.2.3 on 2023-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_lesson_assignments_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='courses', to='quiz.lesson'),
        ),
    ]
